name = "Mads"
uuid = "d6bdc55b-bd94-5012-933c-1f73fc2ee992"
version = "0.7.6"

[deps]
AffineInvariantMCMC = "a0f608ac-68d0-5108-ad9a-0cdca73324f3"
Anasol = "fd9e7046-df80-5870-8bf6-b6b2342464ec"
BlackBoxOptim = "a134a8b2-14d6-55f6-9291-3336d3ab0209"
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocumentFunction = "e1f3b4f0-2dc4-57d3-83f7-d4b7faf3b05b"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterMarkdown = "997ab1e6-3595-5248-9280-8efb232c3433"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Fontconfig = "186bb1d3-e1f7-5a2c-a377-96d770f13627"
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Kriging = "6133562b-a8e8-5ea3-954b-37642b766dad"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
MathProgBase = "fdba3010-5040-5b88-9595-932c9decdf73"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
MetaProgTools = "b1909ce5-9a67-5ea4-ba1b-9d85528f5779"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
NMF = "6ef6ca0d-6ad7-5ff6-b225-e928bfa0a386"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
QuartzImageIO = "dca85d43-d64c-5e67-8c65-017450d5d020"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReusableFunctions = "afbf81f7-602f-5a4a-9a77-738a1b1188fe"
RobustPmap = "27aeedcb-f738-516b-a0b8-3211cf1146e5"
SVR = "22bb73d7-edb2-5785-ba1e-7d60d6824784"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
Anasol = "≥ 0.3.1"
Compat = "≥ 0.13.0"
Compose = "≥ 0.5.2"
Conda = "≥ 0.4.0"
Documenter = "≥ 0.8.10"
DataFrames = "≥ 0.19.1"
Gadfly = "≥ 0.6.5"
Ipopt = "≥ 0.5.0"
JuMP = "≥ 0.19.0"
LsqFit = "≥ 0.3.0"
MathProgBase = "≥ 0.7.0"
PyCall = "≥ 1.8.0"
PyPlot = "≥ 2.2.0"
ReusableFunctions = "≥ 0.2.6"
SVR = "≥ 0.2.3"
StatsBase = "≥ 0.15.0"
julia = "≥ 1.2.0"

[extras]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "Printf"]
